# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-10-16 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewTimeSlot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(blank=True, max_length=250)),
                ('location_id', models.IntegerField()),
                ('appointment_date', models.DateTimeField(null=True)),
                ('date_changed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'global_entry_appointment',
            },
        ),
    ]
