# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-12-10 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewTimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(blank=True, max_length=250)),
                ('location_id', models.IntegerField()),
                ('appointment_date', models.DateTimeField(default=None)),
            ],
            options={
                'db_table': 'global_entry_appointment',
            },
        ),
    ]
