# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-12-11 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_checker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewtimeslot',
            name='changed',
            field=models.BooleanField(default=False),
        ),
    ]
