# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-12-11 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_checker', '0002_interviewtimeslot_changed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewtimeslot',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
