# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-12-11 04:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview_checker', '0003_auto_20191211_0436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interviewtimeslot',
            old_name='changed',
            new_name='date_changed',
        ),
    ]
